# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.cache/wt [current_project]
set_property parent.project_path C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib -sv C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/sources_1/imports/Desktop/SevSeg_4digit.sv
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/sources_1/imports/Desktop/VGAUpdated/VGAUpdated.srcs/sources_1/new/debounce.vhd
  C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/sources_1/imports/Desktop/game.vhd
}
read_vhdl -library xil_defaultlib C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/sources_1/imports/Desktop/VGAUpdated/VGAUpdated.srcs/sources_1/new/vga.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/constrs_1/imports/Projects/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Ali/Desktop/project_gravity_guy_clone/project_gravity_guy_clone.srcs/constrs_1/imports/Projects/Basys3_Master.xdc]


synth_design -top game -part xc7a35tcpg236-1


write_checkpoint -force -noxdef game.dcp

catch { report_utilization -file game_utilization_synth.rpt -pb game_utilization_synth.pb }
